# -*- coding: utf-8 -*-
"""Pregunta19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N6OPuOpLhCXhzGKjYsfh5UwywdqECc_a
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import adfuller, kpss, coint
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.vector_ar.vecm import coint_johansen
from statsmodels.tsa.api import VAR
import warnings
warnings.filterwarnings("ignore")

# Set matplotlib to inline for Colab
# %matplotlib inline

# Upload Excel file
from google.colab import files
print("Please upload the 'Treasury_Bill_Rates_1982_2001.xlsx' Excel file")
uploaded = files.upload()
filename = list(uploaded.keys())[0]
df = pd.read_excel(filename)
print("Columns in dataset:", list(df.columns))

# Extract GS3M and GS6M series
try:
    series1 = pd.to_numeric(df['GS3M'], errors='coerce').dropna()
    series2 = pd.to_numeric(df['GS6M'], errors='coerce').dropna()
    # Ensure both series have the same length and index
    min_len = min(len(series1), len(series2))
    series1 = series1[:min_len]
    series2 = series2[:min_len]
    df_series = pd.DataFrame({'GS3M': series1, 'GS6M': series2})
except KeyError:
    print("Error: Columns 'GS3M' and 'GS6M' not found in the dataset")
    raise

# a. Plot historical series
plt.figure(figsize=(12, 6))
plt.plot(df_series['GS3M'], label='GS3M (3-Month Treasury Bill Rate)', color='blue')
plt.plot(df_series['GS6M'], label='GS6M (6-Month Treasury Bill Rate)', color='orange')
plt.title('Historical Treasury Bill Rates (GS3M and GS6M, 1982-2001)')
plt.xlabel('Time Index')
plt.ylabel('Rate (%)')
plt.legend()
plt.grid(True)
plt.show()
print("\nInterpretation (Time Series Plot):")
print("The plot shows GS3M and GS6M from 1982 to 2001. Both series appear to move closely together, suggesting potential co-movement or a long-run relationship. Visible trends or cycles indicate possible non-stationarity, as rates rise and fall over time. Periods of divergence may reflect short-term market dynamics, but consistent co-movement supports the hypothesis of cointegration.")

# b. Unit Root Tests
def unit_root_tests(series, name):
    result = {
        'name': name,
        'adf_stat': None,
        'adf_p': None,
        'adf_result': '',
        'kpss_stat': None,
        'kpss_p': None,
        'kpss_result': ''
    }

    print(f"\nUnit Root Tests for {name}:")

    # ADF Test
    try:
        adf_result = adfuller(series)
        result['adf_stat'] = adf_result[0]
        result['adf_p'] = adf_result[1]
        result['adf_result'] = 'Stationary' if adf_result[1] < 0.05 else 'Non-stationary'
        print("ADF Test:")
        print(f'  Statistic: {adf_result[0]:.4f}')
        print(f'  p-value: {adf_result[1]:.4f}')
        print(f'  Critical Values: {adf_result[4]}')
        print("  Interpretation:")
        if adf_result[1] < 0.05:
            print(f"    - p-value < 0.05: Reject null - {name} is stationary")
        else:
            print(f"    - p-value >= 0.05: Fail to reject null - {name} may be non-stationary")
    except ValueError as e:
        print(f"ADF Test failed for {name}: {e}")

    # KPSS Test
    try:
        kpss_result = kpss(series, regression='c')
        result['kpss_stat'] = kpss_result[0]
        result['kpss_p'] = kpss_result[1]
        result['kpss_result'] = 'Non-stationary' if kpss_result[1] < 0.05 else 'Stationary'
        print("\nKPSS Test:")
        print(f'  Statistic: {kpss_result[0]:.4f}')
        print(f'  p-value: {kpss_result[1]:.4f}')
        print(f'  Critical Values: {kpss_result[3]}')
        print("  Interpretation:")
        if kpss_result[1] < 0.05:
            print(f"    - p-value < 0.05: Reject null - {name} is non-stationary")
        else:
            print(f"    - p-value >= 0.05: Fail to reject null - {name} may be stationary")
    except ValueError as e:
        print(f"KPSS Test failed for {name}: {e}")

    return result

# Perform unit root tests for both series
gs3m_tests = unit_root_tests(df_series['GS3M'], "GS3M")
gs6m_tests = unit_root_tests(df_series['GS6M'], "GS6M")

# Plot differenced series
gs3m_diff = df_series['GS3M'].diff().dropna()
gs6m_diff = df_series['GS6M'].diff().dropna()
plt.figure(figsize=(12, 6))
plt.plot(gs3m_diff, label='GS3M Differenced', color='blue')
plt.plot(gs6m_diff, label='GS6M Differenced', color='orange')
plt.title('Differenced Treasury Bill Rates (GS3M and GS6M)')
plt.xlabel('Time Index')
plt.ylabel('Differenced Rate')
plt.legend()
plt.grid(True)
plt.show()
print("\nInterpretation (Differenced Series Plot):")
print("The plot shows the first differences of GS3M and GS6M. Unlike the original series, the differenced series fluctuate around zero without clear trends, suggesting that differencing may have removed non-stationarity. Spikes indicate rapid rate changes. If the series appear random and mean-reverting, it supports stationarity after differencing, consistent with unit root test results.")

# c. Cointegration Tests
# Engle-Granger Test
def engle_granger_test(series1, series2):
    print("\nCointegration Test (Engle-Granger):")
    try:
        score, p_value, _ = coint(series1, series2)
        print(f'  Test statistic: {score:.4f}')
        print(f'  p-value: {p_value:.4f}')
        print("  Interpretation:")
        if p_value < 0.05:
            print("    - p-value < 0.05: Reject null - GS3M and GS6M are cointegrated")
        else:
            print("    - p-value >= 0.05: Fail to reject null - GS3M and GS6M may not be cointegrated")
        return p_value < 0.05
    except ValueError as e:
        print(f"Engle-Granger test failed: {e}")
        return False

# Johansen Test
def johansen_test(df):
    print("\nCointegration Test (Johansen):")
    try:
        result = coint_johansen(df, det_order=0, k_ar_diff=1)
        print(f"  Trace Statistic: {result.lr1}")
        print(f"  Critical Values (90%, 95%, 99%): {result.cvt}")
        print("  Interpretation:")
        coint_rank = sum(result.lr1 > result.cvt[:, 1])  # Compare with 95% critical values
        if coint_rank > 0:
            print(f"    - Trace statistic exceeds 95% critical value for r=0: GS3M and GS6M are cointegrated")
        else:
            print(f"    - Trace statistic does not exceed 95% critical value: GS3M and GS6M may not be cointegrated")
        return coint_rank > 0, result
    except ValueError as e:
        print(f"Johansen test failed: {e}")
        return False, None

# Perform cointegration tests
is_coint_eg = engle_granger_test(df_series['GS3M'], df_series['GS6M'])
is_coint_joh, joh_result = johansen_test(df_series)
coint_conclusion = "Cointegrated" if is_coint_eg or is_coint_joh else "Not cointegrated"
print(f"\nCointegration Conclusion: GS3M and GS6M are {coint_conclusion}")

# Plot cointegration residuals if cointegrated
if is_coint_joh and joh_result is not None:
    coint_vec = joh_result.evec[:, 0]  # First cointegrating vector
    residuals = df_series @ coint_vec  # Residuals of cointegrating relationship
    plt.figure(figsize=(12, 6))
    plt.plot(residuals, label='Cointegration Residuals', color='purple')
    plt.title('Residuals of Cointegrating Relationship (GS3M, GS6M)')
    plt.xlabel('Time Index')
    plt.ylabel('Residuals')
    plt.legend()
    plt.grid(True)
    plt.show()
    print("\nInterpretation (Cointegration Residuals Plot):")
    print("The plot shows the residuals of the cointegrating relationship from the Johansen test. Stationary residuals, fluctuating around a constant mean without trends, confirm cointegration. This indicates a stable long-run relationship between GS3M and GS6M, where deviations are temporary and correct over time.")

# d. Economic Meaning
print("\nEconomic Meaning of Cointegration:")
print("If GS3M and GS6M are cointegrated, there exists a long-run equilibrium relationship between the 3-month and 6-month Treasury Bill rates. This implies that, despite short-term fluctuations, the rates move together over time due to shared economic factors like monetary policy, inflation expectations, or market conditions. Cointegration suggests that deviations from this equilibrium are temporary, enabling reliable long-term forecasting or policy analysis.")
print("If not cointegrated, the rates may drift apart without a stable relationship, indicating distinct driving forces. This could complicate forecasting, as movements in one rate may not predict the other, and policy interventions may need to address each rate independently.")

# e. VAR Model Estimation
if gs3m_tests['adf_result'] == 'Non-stationary' or gs6m_tests['adf_result'] == 'Non-stationary':
    print("\nVAR Model Recommendation:")
    print("At least one series is non-stationary (based on ADF test). Use first differences for VAR model.")
    var_data = pd.DataFrame({
        'GS3M_diff': df_series['GS3M'].diff().dropna(),
        'GS6M_diff': df_series['GS6M'].diff().dropna()
    }).dropna()
else:
    print("\nVAR Model Recommendation:")
    print("Both series are stationary (based on ADF test). Use levels for VAR model.")
    var_data = df_series

# Estimate VAR(4) model
try:
    model = VAR(var_data)
    results = model.fit(4)
    print("\nVAR(4) Model Summary:")
    print(results.summary())
except ValueError as e:
    print(f"VAR model estimation failed: {e}")

# Plot Impulse Response Functions
if 'results' in locals():
    irf = results.irf(10)
    fig = irf.plot(orth=False, subplot_params={'fontsize': 10})
    fig.set_size_inches(12, 8)
    fig.suptitle('Impulse Response Functions for VAR(4) Model', fontsize=12)
    plt.tight_layout(rect=[0, 0, 1, 0.95])
    plt.show()
    print("\nInterpretation (Impulse Response Functions Plot):")
    print("The IRF plots show how a one-standard-deviation shock to one series affects both itself and the other over time. Subplots include GS3M to GS3M, GS3M to GS6M, GS6M to GS3M, and GS6M to GS6M responses. Quick decay of responses suggests short-lived effects; persistent responses indicate longer impacts. Significant cross-effects (e.g., GS3M shock affecting GS6M) imply strong interdependence, consistent with cointegration if present.")

# Random Walk Test (retained from provided code)
def random_walk_test(series, name):
    print(f"\nRandom Walk Test for {name}:")
    diff_series = series.diff().dropna()
    var_original = np.var(series)
    var_diff = np.var(diff_series)
    print(f"  Variance of original series: {var_original:.4f}")
    print(f"  Variance of differenced series: {var_diff:.4f}")
    print("  Interpretation:")
    if var_diff < var_original:
        print(f"    - Differenced variance is smaller: {name} may not be a pure random walk")
    else:
        print(f"    - Similar variances: {name} may be a random walk")

random_walk_test(df_series['GS3M'], "GS3M")
random_walk_test(df_series['GS6M'], "GS6M")

# ARIMA Model Selection (retained from provided code)
def find_best_arima(series, name, max_p=3, max_d=2, max_q=3):
    best_aic = float('inf')
    best_order = None
    for p in range(max_p + 1):
        for d in range(max_d + 1):
            for q in range(max_q + 1):
                try:
                    model = ARIMA(series, order=(p, d, q))
                    results = model.fit()
                    if results.aic < best_aic:
                        best_aic = results.aic
                        best_order = (p, d, q)
                except:
                    continue
    if best_order is None:
        print(f"\nNo valid ARIMA model found for {name}")
        return None
    print(f"\nBest ARIMA model for {name}:")
    print(f"  Order: {best_order}")
    print(f"  AIC: {best_aic:.2f}")
    return best_order

# Fit ARIMA models
order1 = find_best_arima(df_series['GS3M'], "GS3M")
order2 = find_best_arima(df_series['GS6M'], "GS6M")
model1 = ARIMA(df_series['GS3M'], order=order1).fit() if order1 else None
model2 = ARIMA(df_series['GS6M'], order=order2).fit() if order2 else None

# Forecast (retained from provided code)
forecast_steps = 30
def plot_forecast(model, series, name, steps=30):
    if model is None:
        print(f"Cannot plot forecast for {name}: No valid model")
        return
    forecast_obj = model.get_forecast(steps=steps)
    forecast = forecast_obj.predicted_mean
    conf_int = forecast_obj.conf_int()
    forecast_index = range(len(series), len(series) + steps)

    plt.figure(figsize=(12, 6))
    plt.plot(series, label=f'{name} Historical')
    plt.plot(forecast_index, forecast, label='Forecast', color='red')
    plt.fill_between(forecast_index,
                     conf_int.iloc[:, 0],
                     conf_int.iloc[:, 1],
                     color='pink',
                     alpha=0.3,
                     label='95% Confidence Interval')
    plt.title(f'{name} Forecast')
    plt.xlabel('Time Index')
    plt.ylabel('Rate (%)')
    plt.legend()
    plt.grid(True)
    plt.show()

    # Forecast interpretation
    last_value = series.iloc[-1]
    mean_forecast = forecast.mean()
    print(f"\nForecast Interpretation for {name}:")
    print(f"  Last observed value: {last_value:.2f}")
    print(f"  Average forecast value: {mean_forecast:.2f}")
    print(f"  95% CI range at period {steps}: [{conf_int.iloc[-1, 0]:.2f}, {conf_int.iloc[-1, 1]:.2f}]")

# Generate forecasts
plot_forecast(model1, df_series['GS3M'], "GS3M")
plot_forecast(model2, df_series['GS6M'], "GS6M")

# Save VAR coefficients to a file (if VAR model was estimated)
if 'results' in locals():
    with open('var_coefficients.txt', 'w') as f:
        f.write(str(results.summary()))